# ref https://raw.githubusercontent.com/nais/naisd/master/nais_example.yaml
image: docker.adeo.no:5000/fo/veientilarbeid
team: warp
replicas:
  min: 2
  max: 4
  cpuThresholdPercentage: 50
port: 8080
healthcheck:
  liveness:
    path: veientilarbeid/internal/isAlive
    initialDelay: 20
  readiness:
    path: veientilarbeid/internal/isReady
    initialDelay: 20
prometheus:
  # NB: pus-decorator sine metrikker
  enabled: true
  path: veientilarbeid/internal/metrics
resources: # Optional. See: http://kubernetes.io/docs/user-guide/compute-resources/
  limits:
    cpu: 3
    memory: 768Mi
  requests:
    memory: 512Mi
fasitResources:
  used:
  - alias: appres.cms
    resourceType: baseUrl
  - alias: appdynamics
    resourceType: applicationproperties
  - alias: loadbalancer:veientilarbeid
    resourceType: loadbalancerconfig
  # oidc med AzureAD B2C
  - alias: aad_b2c_clientid
    resourceType: credential
  - alias: aad_b2c_discovery
    resourceType: baseurl
alertProfiles:
  - common-java-modules

webproxy: true
