# ref https://raw.githubusercontent.com/nais/naisd/master/nais_example.yaml
image: docker.adeo.no:5000/fo/veientilarbeid
team: teamregistrering
replicas:
  min: 2
  max: 4
  cpuThresholdPercentage: 50
port: 8080
healthcheck:
  liveness:
    path: veientilarbeid/internal/isAlive
  readiness:
    path: veientilarbeid/internal/selftest
  readiness:
    path: veientilarbeid/index.html
    initialDelay: 20
prometheus:
  # NB: pus-decorator sine metrikker
  enabled: true
  path: arbeidssokerregistrering/internal/metrics
resources: # Optional. See: http://kubernetes.io/docs/user-guide/compute-resources/
  limits:
    cpu: 3
fasitResources:
  used:
  - alias: appres.cms
    resourceType: baseUrl
  - alias: appdynamics
    resourceType: applicationproperties

  # oidc med AzureAD B2C
  - alias: aad_b2c_clientid
    resourceType: credential
  - alias: aad_b2c_discovery
    resourceType: baseurl
