---
kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veientilarbeid
  namespace: {{ namespace }}
  labels:
    team: paw
spec:
  env:
  - name: APPRES_CMS_URL
    value: {{ appres_cms_url }}
  - name: AAD_B2C_CLIENTID_USERNAME
    value: {{ aad_b2c_clientid_username }}
  - name: AAD_B2C_DISCOVERY_URL
    value: {{ aad_b2c_discovery_url }}
  - name: VEILARBSTEPUP_OIDC_URL
    value: {{ veilarbstepup_oidc_url }}
  - name: VEIENTILARBEID_URL
    value: {{ veientilarbeid_url }}
  - name: AKTIVITETSPLAN_URL
    value: {{ aktivitetsplan_url }}
  - name: VEIVISERARBEIDSSOKER_URL
    value: {{ veiviserarbeidssoker_url }}
  - name: VEILEDEARBEIDSSOKER_URL
    value: {{ veiledearbeidssoker_url }}
  - name: JOBBSOKERKOMPETANSE_URL
    value: {{ jobbsokerkompetanse_url }}
  - name: DITTNAV_LINK_URL
    value: {{ dittnav_link_url }}
  - name: SYFOFRONT_URL
    value: {{ syfofront_url }}
  - name: VEIVISERSOSIALHJELP_URL
    value: {{ veivisersosialhjelp_url }}
  - name: ARBEIDSPLASSEN_URL
    value: {{ arbeidsplassen_url }}
  - name: BEHOVSVURDERING_URL
    value: {{ behovsvurdering_url }}
  - name: FORBEREDE_MOETE_URL
    value: {{ forberedemoete_url }}
  - name: ARBEIDSSOKERREGISTRERING_URL
    value: {{ arbeidssokerregistrering_url }}
  image: {{image}}
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  liveness:
    path: /internal/isAlive
    port: 8080
    initialDelay: 20
  port: 8080
  prometheus:
    enabled: true
    path: /internal/metrics
  readiness:
    path: /internal/isReady
    port: 8080
    initialDelay: 20
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      memory: 512Mi
  webproxy: true
