name: Build, push, and deploy

on:
  push:
    branches:
      - produksjon

env:
  IMAGE_BASE: docker.pkg.github.com/${{github.repository}}/veientilarbeid

jobs:
  test-build-and-push:
    name: Test, build and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: Checkout

      - name: Lag tag for image
        run: echo "::set-env name=TAG::$(git log -1 --pretty='%ad_%h' --date=format:'%Y%m%d%H%M%S')"

      - name: Lag full image referanse
        run: echo "::set-env name=IMAGE::$IMAGE_BASE:$TAG"

      - name: Build app and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build --tag ${IMAGE} .
          echo ${GITHUB_TOKEN} | docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} --password-stdin
          docker push ${IMAGE}

  deploy-q0:
    name: Deploy til Q0
    needs: test-build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: Checkout

      - name: Lag tag for image
        run: echo "::set-env name=TAG::$(git log -1 --pretty='%ad_%h' --date=format:'%Y%m%d%H%M%S')"

      - name: Lag full image referanse
        run: echo "::set-env name=IMAGE::$IMAGE_BASE:$TAG"

      - name: Deploy til Q0
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-sbs
          RESOURCE: nais/nais.yaml
          VARS: nais/vars-q0.yaml
  
  deploy-q1:
    name: Deploy til Q1
    needs: deploy-prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: Checkout

      - name: Lag tag for image
        run: echo "::set-env name=TAG::$(git log -1 --pretty='%ad_%h' --date=format:'%Y%m%d%H%M%S')"

      - name: Lag full image referanse
        run: echo "::set-env name=IMAGE::$IMAGE_BASE:$TAG"

      - name: Deploy til Q1
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-sbs
          RESOURCE: nais/nais.yaml
          VARS: nais/vars-q1.yaml

  deploy-prod:
    name: Deploy til prod
    needs: deploy-q0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: Checkout

      - name: Lag tag for image
        run: echo "::set-env name=TAG::$(git log -1 --pretty='%ad_%h' --date=format:'%Y%m%d%H%M%S')"

      - name: Lag full image referanse
        run: echo "::set-env name=IMAGE::$IMAGE_BASE:$TAG"

      - name: Deploy to Prod
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-sbs
          RESOURCE: nais/nais.yaml
          VARS: nais/vars-p.yaml
          DRY_RUN: true

  release:
    name: Tag and release
    needs: deploy-prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: Checkout

      - name: Lag tag for image
        run: echo "::set-env name=TAG::$(git log -1 --pretty='%ad_%h' --date=format:'%Y%m%d%H%M%S')"

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release/prod@${{ env.TAG }}
          release_name: Release ${{ env.TAG }} to prod
          prerelease: false
  
  deploy-demo:
    name: Deploy demo
    needs: deploy-prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: Checkout
      - run: now --prod --token ${ZEIT_TOKEN} --confirm
        env:
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
  
  take-screenshots:
    name: Ta skjermbilder og last opp
    needs: deploy-demo
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: navikt/screenshots-action@1.0.7
      name: Tar bilde av forsiden
      with:
        url: https://veientilarbeid.nav.party
    - uses: actions/upload-artifact@v1
      name: Laster opp skjermbilder som artifakt
      with:
        name: Screenshots
        path: screenshots
    - run: now screenshots --local-config now-screenshots.json --prod --token ${ZEIT_TOKEN} --confirm
      name: Legger skjermbilder på ZEIT/Now
      env:
        ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
